# Generated by Django 5.0.6 on 2024-05-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(default='null', max_length=100, primary_key=True, serialize=False, verbose_name='usuario'),
        ),
    ]
