# Generated by Django 5.0.6 on 2024-05-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_usuario_id_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
