# Generated by Django 5.0.6 on 2024-05-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_usuario_is_authenticated_alter_usuario_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
