# Generated by Django 5.0.6 on 2024-05-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0008_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, verbose_name='usuario')),
                ('contrasena', models.CharField(default='null', max_length=32, verbose_name='contrasena')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado usuarios')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
