# Generated by Django 5.0.6 on 2024-05-29 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_categoriaprod_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto'},
        ),
    ]
